typedef enum {
  NO_ERROR = 0,
  ERR_PARAMETERS,
  ERR_LWS_INIT,
  ERR_JSON_PARSE,
  ERR_CONNECTION_INIT,
  ERR_CONNECTION,
  ERR_DATA_PATH_EXCEED_MAX_PATH,
  ERR_DATA_FILE_EXCEED_MAX_PATH,
  ERR_API_KEY_EXCEED_MAX_LEN,
  ERR_DATA_FILE_OPEN,
  ERR_DATA_FILE_WRITE,
} error_t;
